using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProyectoExtraClaseWF.LexicalAnalyzer
{
    public enum Category
    {
        ENTERO, DECIMAL, IDENTIFICADOR, MAYOR_QUE, MENOR_QUE, DIFERENTE_QUE, IGUAL_QUE, MAYOR_IGUAL_QUE, MENOR_IGUAL_QUE, SUMA, RESTA, MULTIPLICACION, DIVISION, EOF, ENTRADA_DATOS, LLAVE_ABRE, LLAVE_CIERRA, ASIGNACION, PALABRA_RESERVADA_FINSI, PALABRA_RESERVADA_SI, PALABRA_RESERVADA_SINO, PALABRA_RESERVADA_INICIO, PALABRA_RESERVADA_FIN, GENERAL, PARENTESIS_QUE_ABRE, PARENTESIS_QUE_CIERRA, PALABRA_RESERVADA_IMPRIMIR, PALABRA_RESERVADA_Y, PALABRA_RESERVADA_O
    }
}